import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../components/Nav";
import Categories from "../components/Categories";
import Bio from "../components/Bio";
import Mywork from "../components/Mywork";
import Booking from "../components/Booking";
export default function Home() {
  return (
    <div className="main-body">
      <Head>
        <title>Frontend Mentor | Single-page design portfolio</title>
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon-32x32.png' />
      </Head>
      <Nav />
      <main className={styles.main}>
        <div className={styles.hero}>
          <header className="container">
            <h1>Design solutions made easy</h1>
            <p>With over ten years of experience in various design disciplines, I’m your one-stop shop for your design needs.</p>
          </header>
          <Categories />
        </div>
        <Bio />
        <Mywork />
        <Booking />
      </main>
      <footer>
        <Nav />
      </footer>
    </div>
  );
}
