apiVersion: v1
kind: Service
metadata:
  name: ogidispearl-project-limited-api-v1
  labels:
    run: ogidispearl-project-limited-api-v1
spec:
  ports:
  - port: 3080
    protocol: TCP
  selector:
    app: ogidispearl-project-limited-api-v1
  type: NodePort